### ISSUE TITLE
Please provide a license.

### ISSUE THREAD

**Issue by cerlestes** [victors1681/3dbrain#3]
Hello. Thanks a lot for your project! I'd love to use the animation on a website of mine. As you have published the code to GitHub, I suppose you want people to freely use it, right? 

Since I could not find a license file in the project clarifying this, I'd like to ask you to provide a license file in the project to clear up this question. If you don't know much about licensing and you want to make the code freely available, I'd suggest you choose MIT license, which basically allows everybody to use the project as they wish.

Let me know if you need help with it, I'd be glad to provide you with a pull request that adds an MIT license or similiar open source license.

**Comment by victors1681** [comment]
@cerlestes  I miss this comment, but yes, feel free to play and use it! I'll update the MIT license

**Comment by victors1681** [comment]
Done
